### ISSUE TITLE
页面同时引入SUI.Moble时会发生冲突

### ISSUE THREAD

**Issue by icmr** [efri-yang/mobileValidate#14]
$.fn.mvalidateDestroy=function(){
		var $form=$(this),$fields,
			dataValidate=$form.data(name);
		if($form.is('form') && $.isPlainObject(dataValidate) && **typeof(dataValidate.options.namespace) == 'string'**) {
			$fields = $form.removeData(name).find(allTypes);
			$fields.off('.' + dataValidate.options.namespace);
		}	
		return $form;
	};

这句代码“typeof(dataValidate.options.namespace) == 'string' ”，报没有namespace，因为options是undefined

不知道应该如何解决，请教是否有解决方法？谢谢。

**Comment by efri-yang** [comment]
最新版本已经修复了
