### ISSUE TITLE
zepto-mvalidate.js:291   有个条件会是 undefine 从而导致报错 

### ISSUE THREAD

**Issue by silentzone** [efri-yang/mobileValidate#6]
zepto-mvalidate.js:291 ：
`if ($form.is('form') && $.isPlainObject(dataValidate) && typeof(dataValidate.options.nameSpace) == 'string')`

 Uncaught TypeError: Cannot read property 'nameSpace' of undefined

**Comment by efri-yang** [comment]
对象属性的额大小写问题,已经修复了

**Comment by simlegate** [comment]
@efri-yang `290行：dataValidate=$form.data(name);` 这个name变量在哪儿赋值或者定义的？

**Comment by efri-yang** [comment]
已修复
