### ISSUE TITLE
大家千万别下zepto版

### ISSUE THREAD

**Issue by cocody** [efri-yang/mobileValidate#8]
大家千万别下zepto版,压根不能用,zepto是没有 data(),储存对象这个方法的,但源码偏偏有,好了,下个data.js解决了,又会出现另外几个问题.jquery版暂时正常

**Comment by cocody** [comment]
data()方法是导致 namespace 错误原因

**Comment by efri-yang** [comment]
出现什么问题能不能贴出来，插件本身在zepto下是需要data.js插件

**Comment by cocody** [comment]
加入了data.js插件好像也是工作不能,所以用jquery版本没那么多烦恼

**Comment by efri-yang** [comment]
我回去再测试一下
